### PR TITLE
Fix make install paths

### PR DESCRIPTION
**Pull request by amilcarlucas**
I have no clue why this has not been fixed in the reach branch yet !!!

### CODE REVIEW

**Comment by egorf** [comment]
@amilcarlucas This will only work on Reach modules. In any other situation, it will fail due to missing directories. If you create the paths, many useful files from the RTKLIB tree will be missing, including configs and such. 

I agree the install part is not usable as it is, but I think the makefile needs to be universal.

**Comment by amilcarlucas** [comment]
This patch is to the reach branch, that should only work on reach modules. I do not get your point.
The makefile does not need to be universal.

Anyway I got a better patch now that speeds up the compilation on the edison :)
So I will do a new pull request with that.

**Comment by egorf** [comment]
> This patch is to the reach branch, that should only work on reach modules. I do not get your point.

We might add some features that are wanted on the Reach modules, but we don't do anything that makes the package less usable on other platforms. The reach branch is just our master equivalent.

**Comment by amilcarlucas** [comment]
I have now a better solution for this issue: https://github.com/emlid/reach-docs/pull/25

**Pull request closed without merging**
